### ISSUE TITLE
JSON file missing in iRODS

### ISSUE THREAD

**Issue by feltus** [biggstd/pynome#1]
Hi.

In transferring iRODS genome data to Colorado State for the NDN project, I noticed that these things (see 'ils' example below)

1. There is no JSON file with metadata in iRODs.  Does that file include Taxonomy IDs?  That is very important and maybe should be in directory name?
2. Remove the '.txt' from '*.Splice.sites.txt' names

[ffeltus@scidas-scratch1 MG2]$ ils
/scidasZone/sysbio/genomes/Zymoseptoria_tritici/MG2:
  Zymoseptoria_tritici-MG2.1.ht2
  Zymoseptoria_tritici-MG2.2.ht2
  Zymoseptoria_tritici-MG2.3.ht2
  Zymoseptoria_tritici-MG2.4.ht2
  Zymoseptoria_tritici-MG2.5.ht2
  Zymoseptoria_tritici-MG2.6.ht2
  Zymoseptoria_tritici-MG2.7.ht2
  Zymoseptoria_tritici-MG2.8.ht2
  Zymoseptoria_tritici-MG2.fa
  Zymoseptoria_tritici-MG2.gff3
  Zymoseptoria_tritici-MG2.gtf
  Zymoseptoria_tritici-MG2.Splice_sites.txt

**Comment by spficklin** [comment]
Hey @feltus . According to OSG-GEM documentation that Splice_sites file should have a .txt extension.  Has the extension been removed from that workflow too?

**Comment by feltus** [comment]
Oh.  Let's leave it as is.


Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Stephen Ficklin <notifications@github.com> Date: 2/13/18  4:31 PM  (GMT-05:00) To: SystemsGenetics/pynome <pynome@noreply.github.com> Cc: Alex Feltus <alex.feltus@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [SystemsGenetics/pynome] JSON file missing in iRODS (#1) 
Hey @feltus . According to OSG-GEM documentation that Splice_sites file should have a .txt extension.  Has the extension been removed from that workflow too?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/SystemsGenetics/pynome","title":"SystemsGenetics/pynome","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/SystemsGenetics/pynome"}},"updates":{"snippets":[{"icon":"PERSON","message":"@spficklin in #1: Hey @feltus . According to OSG-GEM documentation that Splice_sites file should have a .txt extension.  Has the extension been removed from that workflow too?"}],"action":{"name":"View Issue","url":"https://github.com/SystemsGenetics/pynome/issues/1#issuecomment-365410912"}}}
